server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # /qr resolves to qr.html
    location = /qr {
        try_files /qr.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
